# Generated by Django 4.0.2 on 2022-02-12 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_pass', models.DateField(blank=True, null=True)),
                ('board', models.CharField(choices=[('cbse', 'cbse'), ('JAC', 'JAC'), ('skmu', 'skmu'), ('bbkmu', 'bbkmu')], max_length=200, null=True)),
                ('exam_passed', models.CharField(choices=[('10', '10'), ('12', '12'), ('diploma', 'Diploma'), ('Graduation', 'Graduation')], max_length=200, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.person')),
            ],
        ),
    ]
