# Generated by Django 4.0.2 on 2022-02-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='cgpa_perc',
            field=models.CharField(choices=[('CGPA', 'CGPA'), ('percentage', 'percentage')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='roll_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='board',
            field=models.CharField(choices=[('cbse', 'cbse'), ('JAC', 'JAC'), ('skmu', 'skmu'), ('bbkmu', 'bbkmu'), ('sbtej', 'SBTE,Jharkhand')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='exam_passed',
            field=models.CharField(choices=[('10', '10'), ('12', '12'), ('diploma', 'diploma'), ('Graduation', 'Graduation')], max_length=200, null=True),
        ),
    ]
