# Generated by Django 4.0.2 on 2022-02-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_education_cgpa_perc_education_roll_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='scored',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
