# Generated by Django 3.2.5 on 2022-02-12 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_person_father'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='son', to='person.person'),
        ),
    ]
