# Generated by Django 3.2.5 on 2022-02-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20220213_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cast',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='resident',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
