# Generated by Django 3.2.5 on 2022-02-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_auto_20220213_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='voter_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
