# Generated by Django 3.2.5 on 2022-02-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_person_voter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='PAN',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='vaccine',
            field=models.CharField(choices=[('covidshield', (('1st', '1st'), ('2nd', '2nd'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='exam_passed',
            field=models.CharField(choices=[('ITI', 'ITI'), ('10', '10'), ('12', '12'), ('diploma', 'diploma'), ('Graduation', 'Graduation')], max_length=200, null=True),
        ),
    ]
