# Generated by Django 3.2.5 on 2022-02-14 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_auto_20220214_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='PAN',
            new_name='pan',
        ),
    ]
