# Generated by Django 3.2.5 on 2022-02-14 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_rename_pan_person_pan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pan',
        ),
    ]
