# Generated by Django 3.2.5 on 2022-02-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_remove_person_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pan_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='vaccine',
            field=models.CharField(choices=[('covidshield', (('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'))), ('cowaxin', (('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'))), ('unknown', 'Unknown')], max_length=200, null=True),
        ),
    ]
