# Generated by Django 3.2.5 on 2022-02-14 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_auto_20220214_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='vaccine',
            field=models.CharField(choices=[('covidshield', (('CS1st', 'CS1st'), ('CS2nd', 'CS2nd'), ('CS3rd', 'CS3rd'))), ('cowaxin', (('CW1st', 'CW1st'), ('CW2nd', 'CW2nd'), ('CW3rd', 'CW3rd'))), ('unknown', 'Unknown')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Jharsewa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.DateField(null=True)),
                ('type', models.CharField(choices=[('resident', 'resident'), ('cast', 'cast')], max_length=200, null=True)),
                ('cert_no', models.CharField(max_length=200, null=True)),
                ('token_no', models.CharField(max_length=200, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.person')),
            ],
        ),
    ]
