# Generated by Django 3.2.5 on 2022-02-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0014_auto_20220214_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='person',
            name='resident',
        ),
    ]
