# Generated by Django 3.2.5 on 2022-02-14 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0015_auto_20220214_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('uida', 'uida'), ('pan', 'pan'), ('voter_id', 'voter_id')], max_length=200, null=True)),
                ('cert_no', models.CharField(max_length=200, null=True)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('person', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.person')),
            ],
        ),
    ]
