# Generated by Django 3.2.5 on 2022-02-14 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0017_alter_identy_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pan_no',
        ),
        migrations.RemoveField(
            model_name='person',
            name='uida',
        ),
        migrations.RemoveField(
            model_name='person',
            name='voter_id',
        ),
        migrations.AlterField(
            model_name='person',
            name='father',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baba', to='person.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='vaccine',
            field=models.CharField(blank=True, choices=[('covidshield', (('CS1st', 'CS1st'), ('CS2nd', 'CS2nd'), ('CS3rd', 'CS3rd'))), ('cowaxin', (('CW1st', 'CW1st'), ('CW2nd', 'CW2nd'), ('CW3rd', 'CW3rd'))), ('unknown', 'Unknown')], max_length=200, null=True),
        ),
    ]
