# Generated by Django 3.2.5 on 2022-02-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0024_alter_person_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jharsewa',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='jhar/'),
        ),
    ]
