# Generated by Django 3.2.5 on 2022-02-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0025_jharsewa_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='admit',
            field=models.FileField(blank=True, null=True, upload_to='admit/'),
        ),
        migrations.AddField(
            model_name='education',
            name='marksheet',
            field=models.FileField(blank=True, null=True, upload_to='marksheet/'),
        ),
        migrations.AddField(
            model_name='education',
            name='passing',
            field=models.FileField(blank=True, null=True, upload_to='pass/'),
        ),
        migrations.AddField(
            model_name='identy',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='id/'),
        ),
    ]
