# Generated by Django 3.2.5 on 2022-02-23 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0026_auto_20220223_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identy',
            old_name='document',
            new_name='idcard',
        ),
    ]
