# Generated by Django 3.2.5 on 2022-02-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0028_remove_identy_idcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jharsewa',
            name='document',
        ),
    ]
