# Generated by Django 3.2.5 on 2022-02-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0029_remove_jharsewa_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='jharsewa',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='jhar/'),
        ),
    ]
