# Generated by Django 3.2.5 on 2022-02-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0030_jharsewa_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='identy',
            name='idcard',
            field=models.FileField(blank=True, null=True, upload_to='id/'),
        ),
    ]
