# Generated by Django 3.2.5 on 2022-02-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0039_identy_idcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jharsewa',
            name='date_of_issue',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jharsewa',
            name='document',
            field=models.FileField(default='default.jpg', upload_to='jhar/'),
        ),
    ]
