# Generated by Django 3.2.5 on 2022-02-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0040_auto_20220226_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jharsewa',
            name='date_of_issue',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
