# Generated by Django 3.2.5 on 2022-02-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0041_alter_jharsewa_date_of_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jharsewa',
            name='date_of_issue',
            field=models.DateField(null=True),
        ),
    ]
