# Generated by Django 3.2.5 on 2022-02-26 03:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0042_alter_jharsewa_date_of_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jharsewa',
            name='date_of_issue',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
