# Generated by Django 3.2.5 on 2022-02-26 12:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0046_alter_jharsewa_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='year_of_pass',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='identy',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.person'),
        ),
    ]
