# Generated by Django 3.2.5 on 2022-03-08 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0051_alter_identy_idcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_pass', models.DateField()),
                ('exam_passed', models.CharField(choices=[('Tech', (('sem1', 'sem1'), ('sem2', 'sem2'), ('sem3', 'sem3'), ('sem4', 'sem4'), ('sem5', 'sem5'), ('sem6', 'sem6'), ('sem7', 'sem7'), ('sem8', 'sem8'))), ('General_6sem_Graduate', (('sem1', 'sem1'), ('sem2', 'sem2'), ('sem3', 'sem3'), ('sem4', 'sem4'), ('sem5', 'sem5'), ('sem6', 'sem6'))), ('General_3yr_Graduate', (('part1', 'part1'), ('part2', 'part2'), ('part3', 'part3'))), ('final', 'final')], max_length=200, null=True)),
                ('admit', models.FileField(blank=True, null=True, upload_to='admit_sp/')),
                ('marksheet', models.FileField(blank=True, null=True, upload_to='marksheet_sp/')),
                ('specialisation', models.CharField(max_length=200, null=True)),
                ('cgpa_perc', models.CharField(choices=[('CGPA', 'CGPA'), ('percentage', 'percentage')], max_length=200, null=True)),
                ('scored', models.CharField(max_length=200, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.person')),
            ],
        ),
    ]
